export type UiLanguage = 'en' | 'hi'

const catalogs = {
  en: {
    uiLanguage: 'UI language',
    english: 'English',
    hindi: 'हिन्दी',
    conversation: 'Research conversation',
    threadTranscript: 'THREAD TRANSCRIPT',
    savedThread: 'Saved to this thread',
    unavailable: 'Chat is unavailable',
    loadingConversation: 'Could not load this conversation.',
    askSources: 'Ask a question about your sources',
    askPlaceholder: 'Ask a question about your sources…',
    configureModel: 'Configure a model to start a conversation',
    answerLanguage: 'Answer language',
    retrievalProfile: 'Retrieval profile',
    basicRetrieval: 'Basic retrieval',
    advancedRetrieval: 'Advanced retrieval',
    activeRun: 'A run is active',
    enterToSend: 'Enter to send · Shift + Enter for a new line',
    sendMessage: 'Send message',
    sourcesUnchanged: 'Sources remain unchanged',
    referencesKept: 'ANSWERS KEEP THEIR REFERENCES',
    voice: 'Voice input',
    startRecording: 'Start recording',
    stopRecording: 'Stop recording',
    recording: 'Recording… release tracks when stopped',
    chooseAudio: 'Choose audio',
    transcribing: 'Transcribing…',
    transcriptionReady:
      'Transcript added to the draft. Review it, then press Send.',
    sttUnavailable: 'Speech recognition is unavailable',
    unsupportedBrowser: 'This browser does not support microphone recording.',
    microphoneDenied:
      'Microphone access was denied. Check browser permissions.',
    audioTooLarge: 'Audio must be 10 MB or smaller.',
    audioTooLong: 'Recording stopped at the 120 second limit.',
    audioFailed: 'Could not transcribe this audio.',
    emptyTranscript: 'No speech was recognized. Your draft was left unchanged.',
    translationUnavailable: 'Translation is unavailable',
    ttsUnavailable: 'Voice playback is unavailable',
    selectSources: 'Choose sources',
    sourceFailed: 'Source unavailable',
    upload: 'Upload files',
    uploadFailed: 'Upload failed',
    connection: 'Database connection',
    connectionFailed: 'Connection failed',
    nameRequired: 'Name is required',
    cancel: 'Cancel',
    retry: 'Retry',
  },
  hi: {
    uiLanguage: 'इंटरफ़ेस भाषा',
    english: 'English',
    hindi: 'हिन्दी',
    conversation: 'शोध बातचीत',
    threadTranscript: 'बातचीत का लेखा',
    savedThread: 'इस थ्रेड में सहेजा गया',
    unavailable: 'चैट उपलब्ध नहीं है',
    loadingConversation: 'यह बातचीत लोड नहीं हो सकी।',
    askSources: 'अपने स्रोतों के बारे में सवाल पूछें',
    askPlaceholder: 'अपने स्रोतों के बारे में सवाल पूछें…',
    configureModel: 'बातचीत शुरू करने के लिए मॉडल सेट करें',
    answerLanguage: 'उत्तर की भाषा',
    retrievalProfile: 'खोज प्रोफ़ाइल',
    basicRetrieval: 'साधारण खोज',
    advancedRetrieval: 'उन्नत खोज',
    activeRun: 'काम चल रहा है',
    enterToSend: 'भेजने के लिए Enter · नई पंक्ति के लिए Shift + Enter',
    sendMessage: 'संदेश भेजें',
    sourcesUnchanged: 'स्रोतों में बदलाव नहीं होगा',
    referencesKept: 'उत्तर में संदर्भ बने रहेंगे',
    voice: 'आवाज़ से लिखें',
    startRecording: 'रिकॉर्डिंग शुरू करें',
    stopRecording: 'रिकॉर्डिंग रोकें',
    recording: 'रिकॉर्डिंग… रोकने पर माइक्रोफ़ोन बंद होगा',
    chooseAudio: 'ऑडियो चुनें',
    transcribing: 'लिखित रूप बनाया जा रहा है…',
    transcriptionReady: 'लिखित पाठ ड्राफ़्ट में जुड़ गया। जाँचकर भेजें।',
    sttUnavailable: 'वाक् पहचान उपलब्ध नहीं है',
    unsupportedBrowser:
      'इस ब्राउज़र में माइक्रोफ़ोन रिकॉर्डिंग उपलब्ध नहीं है।',
    microphoneDenied:
      'माइक्रोफ़ोन की अनुमति नहीं मिली। ब्राउज़र सेटिंग जाँचें।',
    audioTooLarge: 'ऑडियो 10 MB या उससे कम होना चाहिए।',
    audioTooLong: '120 सेकंड की सीमा पर रिकॉर्डिंग रोक दी गई।',
    audioFailed: 'इस ऑडियो को लिखित रूप में नहीं बदला जा सका।',
    emptyTranscript: 'आवाज़ पहचानी नहीं गई। आपका ड्राफ़्ट नहीं बदला।',
    translationUnavailable: 'अनुवाद उपलब्ध नहीं है',
    ttsUnavailable: 'आवाज़ में सुनाना उपलब्ध नहीं है',
    selectSources: 'स्रोत चुनें',
    sourceFailed: 'स्रोत उपलब्ध नहीं है',
    upload: 'फ़ाइलें अपलोड करें',
    uploadFailed: 'अपलोड विफल हुआ',
    connection: 'डेटाबेस कनेक्शन',
    connectionFailed: 'कनेक्शन विफल हुआ',
    nameRequired: 'नाम आवश्यक है',
    cancel: 'रद्द करें',
    retry: 'फिर कोशिश करें',
  },
} satisfies Record<UiLanguage, Record<string, string>>

export type UiTextKey = keyof (typeof catalogs)['en']

export function uiText(language: UiLanguage, key: UiTextKey): string {
  return catalogs[language][key]
}
